on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

name: Windows build

jobs:
    test-windows:
        runs-on: ${{ matrix.os }}
        name: ${{ matrix.os }} (${{ matrix.python-version}})
        strategy:
            fail-fast: false
            matrix:
              os: ["windows-latest"]
              python-version: ["3.10","3.11"]
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
                lfs: true
          - name: Install miniconda
            uses: conda-incubator/setup-miniconda@v2
            with:
              auto-activate-base: true
              python-version: ${{ matrix.python-version}}
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install --user --no-cache-dir Cython
                pip install --user -r requirements.txt
                pip install --user -r requirements_dev.txt
          - name: Test with pytest
            run: |
                python -m unittest discover test/
                python -m pytest test/
          - name: Train example
            run: |
                python train.py --data_name cifar10 --model iglvq --train_norm lpips-l2 --test_norm l1 --feature_extraction --prune --prune_mode easy --prune_fraction 0.8
                
          
          
